global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user_api'
    static_configs:
      - targets: ['user_api:8000']

  - job_name: 'booking_api'
    static_configs:
      - targets: ['booking_api:3000']


